# Generated by Django 4.0.5 on 2022-07-07 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_autor_marca_livro'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Marca',
        ),
    ]
