# Generated by Django 4.0.5 on 2022-07-07 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_marca'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Autor',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='editora',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Editora',
        ),
        migrations.DeleteModel(
            name='Livro',
        ),
    ]
