# Generated by Django 4.1 on 2022-09-06 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_autor_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='ISBN',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
